# Disk Usage Prometheus Exporter Configuration with Background Caching
# This configuration enables background caching for better performance

# Basic configuration
# analyzed-path: "/mnt/meta-test"
# analyzed-path: "/home/kklee228"
analyzed-path: "/"
# analyzed-path: "/srv/nfs/shared/meta-test"
bind-address: "0.0.0.0:9996"
dir-level: 3
mode: "http"
follow-symlinks: false

# Log level configuration
# Available levels: trace, debug, info, warn, error, fatal, panic
log-level: "debug"

# CPU cores configuration
# Maximum number of CPU cores to use for parallel processing
max-procs: 12

# Whether to collect node_disk_usage_directory_count
dir-count: false

# Whether to collect node_disk_usage_file_count
file-count: false

# Whether to collect node_disk_usage_size_bucket
size-bucket: true

# Background caching configuration
# Both storage-path and scan-interval-minutes must be set to enable caching
storage-path: "/tmp/disk-usage-cache"
scan-interval-minutes: 1

# if true, caching data to disk
disk-caching: true

# Directories to ignore during analysis
ignore-dirs:
  - /proc
  - /dev
  - /sys
  - /run
  - /var/cache/rsnapshot
  - /tmp