# Disk Usage Prometheus Exporter Configuration with Multiple Paths
# This configuration monitors multiple directories with different depth levels

# Basic configuration
bind-address: "0.0.0.0:9996"
mode: "http"
follow-symlinks: false

# Log level configuration
# Available levels: trace, debug, info, warn, error, fatal, panic
log-level: "debug"

# CPU cores configuration
# Maximum number of CPU cores to use for parallel processing
max-procs: 4

# Multiple paths configuration
# Each path can have different directory depth levels
multi-paths:
  /home: 2
  /var: 3
  /tmp: 1
  /opt: 2

# Background caching configuration (optional)
storage-path: "/tmp/disk-usage-cache"
scan-interval-minutes: 20

# Directories to ignore during analysis
ignore-dirs:
  - /proc
  - /dev
  - /sys
  - /run
  - /var/cache/rsnapshot

# Basic authentication (optional)
# Passwords must be bcrypt hashed
# basic-auth-users:
#   admin: $2b$12$hNf2lSsxfm0.i4a.1kVpSOVyBCfIB51VRjgBUyv6kdnyTlgWj81Ay