# Disk Usage Prometheus Exporter Configuration
# This is an example configuration file for disk_usage_exporter

# Basic configuration
analyzed-path: "/mnt"
bind-address: "0.0.0.0:9995"
dir-level: 1
mode: "http"
follow-symlinks: false

# Background caching configuration (optional)
# Both storage-path and scan-interval-minutes must be set to enable caching
storage-path: "/tmp/gdu-cache"
scan-interval-minutes: 30

# Directories to ignore during analysis
ignore-dirs:
  - /proc
  - /dev
  - /sys
  - /run
  - /var/cache/rsnapshot
  - /tmp

# Multiple paths configuration (alternative to analyzed-path)
# Uncomment and configure as needed
# multi-paths:
#   /home: 2
#   /var: 3
#   /tmp: 1

# Basic authentication (optional)
# Passwords must be bcrypt hashed
# basic-auth-users:
#   admin: $2b$12$hNf2lSsxfm0.i4a.1kVpSOVyBCfIB51VRjgBUyv6kdnyTlgWj81Ay
#   user: $2b$12$MzUQjmLxPRM9WW6OI4ZzwuZHB7ubHiiSnngJxIufgZms27nw.5ZAq

# File output mode configuration (alternative to http mode)
# Uncomment to enable file output mode
# mode: "file"
# output-file: "./disk-usage-exporter.prom"