# Basic Disk Usage Prometheus Exporter Configuration
# This configuration runs without background caching (live analysis mode)

# Basic configuration
analyzed-path: "/tmp"
bind-address: "0.0.0.0:9995"
dir-level: 1
mode: "http"
follow-symlinks: false

# Directories to ignore during analysis
ignore-dirs:
  - /proc
  - /dev
  - /sys
  - /run
  - /var/cache/rsnapshot